package edu.miami.ccs.dcic;
// default package
// Generated Aug 17, 2018 6:18:33 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AutosuggestTempId generated by hbm2java
 */
@Embeddable
public class AutosuggestTempId implements java.io.Serializable {

	private Integer hitObjectId;
	private String suggestTerm;
	private String hitObjectClass;
	private String suggestObjectTable;
	private String suggestObjectClass;
	private String hitObjectPreferredName;

	public AutosuggestTempId() {
	}

	public AutosuggestTempId(Integer hitObjectId, String suggestTerm, String hitObjectClass, String suggestObjectTable,
			String suggestObjectClass, String hitObjectPreferredName) {
		this.hitObjectId = hitObjectId;
		this.suggestTerm = suggestTerm;
		this.hitObjectClass = hitObjectClass;
		this.suggestObjectTable = suggestObjectTable;
		this.suggestObjectClass = suggestObjectClass;
		this.hitObjectPreferredName = hitObjectPreferredName;
	}

	@Column(name = "hit_object_id")
	public Integer getHitObjectId() {
		return this.hitObjectId;
	}

	public void setHitObjectId(Integer hitObjectId) {
		this.hitObjectId = hitObjectId;
	}

	@Column(name = "suggest_term")
	public String getSuggestTerm() {
		return this.suggestTerm;
	}

	public void setSuggestTerm(String suggestTerm) {
		this.suggestTerm = suggestTerm;
	}

	@Column(name = "hit_object_class", length = 80)
	public String getHitObjectClass() {
		return this.hitObjectClass;
	}

	public void setHitObjectClass(String hitObjectClass) {
		this.hitObjectClass = hitObjectClass;
	}

	@Column(name = "suggest_object_table", length = 80)
	public String getSuggestObjectTable() {
		return this.suggestObjectTable;
	}

	public void setSuggestObjectTable(String suggestObjectTable) {
		this.suggestObjectTable = suggestObjectTable;
	}

	@Column(name = "suggest_object_class", length = 80)
	public String getSuggestObjectClass() {
		return this.suggestObjectClass;
	}

	public void setSuggestObjectClass(String suggestObjectClass) {
		this.suggestObjectClass = suggestObjectClass;
	}

	@Column(name = "hit_object_preferred_name")
	public String getHitObjectPreferredName() {
		return this.hitObjectPreferredName;
	}

	public void setHitObjectPreferredName(String hitObjectPreferredName) {
		this.hitObjectPreferredName = hitObjectPreferredName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AutosuggestTempId))
			return false;
		AutosuggestTempId castOther = (AutosuggestTempId) other;

		return ((this.getHitObjectId() == castOther.getHitObjectId()) || (this.getHitObjectId() != null
				&& castOther.getHitObjectId() != null && this.getHitObjectId().equals(castOther.getHitObjectId())))
				&& ((this.getSuggestTerm() == castOther.getSuggestTerm())
						|| (this.getSuggestTerm() != null && castOther.getSuggestTerm() != null
								&& this.getSuggestTerm().equals(castOther.getSuggestTerm())))
				&& ((this.getHitObjectClass() == castOther.getHitObjectClass())
						|| (this.getHitObjectClass() != null && castOther.getHitObjectClass() != null
								&& this.getHitObjectClass().equals(castOther.getHitObjectClass())))
				&& ((this.getSuggestObjectTable() == castOther.getSuggestObjectTable())
						|| (this.getSuggestObjectTable() != null && castOther.getSuggestObjectTable() != null
								&& this.getSuggestObjectTable().equals(castOther.getSuggestObjectTable())))
				&& ((this.getSuggestObjectClass() == castOther.getSuggestObjectClass())
						|| (this.getSuggestObjectClass() != null && castOther.getSuggestObjectClass() != null
								&& this.getSuggestObjectClass().equals(castOther.getSuggestObjectClass())))
				&& ((this.getHitObjectPreferredName() == castOther.getHitObjectPreferredName())
						|| (this.getHitObjectPreferredName() != null && castOther.getHitObjectPreferredName() != null
								&& this.getHitObjectPreferredName().equals(castOther.getHitObjectPreferredName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getHitObjectId() == null ? 0 : this.getHitObjectId().hashCode());
		result = 37 * result + (getSuggestTerm() == null ? 0 : this.getSuggestTerm().hashCode());
		result = 37 * result + (getHitObjectClass() == null ? 0 : this.getHitObjectClass().hashCode());
		result = 37 * result + (getSuggestObjectTable() == null ? 0 : this.getSuggestObjectTable().hashCode());
		result = 37 * result + (getSuggestObjectClass() == null ? 0 : this.getSuggestObjectClass().hashCode());
		result = 37 * result + (getHitObjectPreferredName() == null ? 0 : this.getHitObjectPreferredName().hashCode());
		return result;
	}

}
