package edu.miami.ccs.dcic;
// default package
// Generated Aug 19, 2018 10:25:58 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CellLine generated by hbm2java
 */
@Entity
@Table(name = "cell_line", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "cell_line_id"))
public class CellLine implements java.io.Serializable {

	private int modelSystemId;
	private String modelSystemClass;
	private Integer cellLineId;
	private String cellLineName;
	private String organ;
	private String precursorCellName;
	private String tissue;

	public CellLine() {
	}

	public CellLine(int modelSystemId) {
		this.modelSystemId = modelSystemId;
	}

	public CellLine(int modelSystemId, String modelSystemClass, Integer cellLineId, String cellLineName, String organ,
			String precursorCellName, String tissue) {
		this.modelSystemId = modelSystemId;
		this.modelSystemClass = modelSystemClass;
		this.cellLineId = cellLineId;
		this.cellLineName = cellLineName;
		this.organ = organ;
		this.precursorCellName = precursorCellName;
		this.tissue = tissue;
	}

	@Id

	@Column(name = "model_system_id", unique = true, nullable = false)
	public int getModelSystemId() {
		return this.modelSystemId;
	}

	public void setModelSystemId(int modelSystemId) {
		this.modelSystemId = modelSystemId;
	}

	@Column(name = "model_system_class", length = 80)
	public String getModelSystemClass() {
		return this.modelSystemClass;
	}

	public void setModelSystemClass(String modelSystemClass) {
		this.modelSystemClass = modelSystemClass;
	}

	@Column(name = "cell_line_id", unique = true)
	public Integer getCellLineId() {
		return this.cellLineId;
	}

	public void setCellLineId(Integer cellLineId) {
		this.cellLineId = cellLineId;
	}

	@Column(name = "cell_line_name")
	public String getCellLineName() {
		return this.cellLineName;
	}

	public void setCellLineName(String cellLineName) {
		this.cellLineName = cellLineName;
	}

	@Column(name = "organ", length = 80)
	public String getOrgan() {
		return this.organ;
	}

	public void setOrgan(String organ) {
		this.organ = organ;
	}

	@Column(name = "precursor_cell_name", length = 80)
	public String getPrecursorCellName() {
		return this.precursorCellName;
	}

	public void setPrecursorCellName(String precursorCellName) {
		this.precursorCellName = precursorCellName;
	}

	@Column(name = "tissue")
	public String getTissue() {
		return this.tissue;
	}

	public void setTissue(String tissue) {
		this.tissue = tissue;
	}

}
