package edu.miami.ccs.dcic;
// default package
// Generated Aug 19, 2018 10:25:58 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ipsc generated by hbm2java
 */
@Entity
@Table(name = "ipsc", schema = "public")
public class Ipsc implements java.io.Serializable {

	private int modelSystemId;
	private String modelSystemClass;
	private Integer ipscId;
	private String ipName;
	private Integer ipPrecursorCell;

	public Ipsc() {
	}

	public Ipsc(int modelSystemId) {
		this.modelSystemId = modelSystemId;
	}

	public Ipsc(int modelSystemId, String modelSystemClass, Integer ipscId, String ipName, Integer ipPrecursorCell) {
		this.modelSystemId = modelSystemId;
		this.modelSystemClass = modelSystemClass;
		this.ipscId = ipscId;
		this.ipName = ipName;
		this.ipPrecursorCell = ipPrecursorCell;
	}

	@Id

	@Column(name = "model_system_id", unique = true, nullable = false)
	public int getModelSystemId() {
		return this.modelSystemId;
	}

	public void setModelSystemId(int modelSystemId) {
		this.modelSystemId = modelSystemId;
	}

	@Column(name = "model_system_class", length = 80)
	public String getModelSystemClass() {
		return this.modelSystemClass;
	}

	public void setModelSystemClass(String modelSystemClass) {
		this.modelSystemClass = modelSystemClass;
	}

	@Column(name = "ipsc_id")
	public Integer getIpscId() {
		return this.ipscId;
	}

	public void setIpscId(Integer ipscId) {
		this.ipscId = ipscId;
	}

	@Column(name = "ip_name")
	public String getIpName() {
		return this.ipName;
	}

	public void setIpName(String ipName) {
		this.ipName = ipName;
	}

	@Column(name = "ip_precursor_cell")
	public Integer getIpPrecursorCell() {
		return this.ipPrecursorCell;
	}

	public void setIpPrecursorCell(Integer ipPrecursorCell) {
		this.ipPrecursorCell = ipPrecursorCell;
	}

}
